#!/bin/bash
# PRODUCTION DEPLOYMENT GUIDE
# Fix verification flow - Add missing idempotency_key column

echo "🚀 NAMASKAH PRODUCTION FIX DEPLOYMENT"
echo "======================================"
echo ""
echo "⚠️  CRITICAL: This fixes verification creation failures"
echo ""

# Step 1: Backup
echo "📦 Step 1: Backup Database"
echo "Run on Render.com dashboard or via CLI:"
echo "  pg_dump \$DATABASE_URL > backup_$(date +%Y%m%d_%H%M%S).sql"
echo ""
read -p "Press Enter when backup is complete..."

# Step 2: Deploy Code
echo ""
echo "📤 Step 2: Deploy Code Changes"
echo "Code has been pushed to main branch"
echo "Render.com will auto-deploy or run:"
echo "  git pull origin main"
echo ""
read -p "Press Enter when code is deployed..."

# Step 3: Run Migration
echo ""
echo "🔧 Step 3: Run Database Migration"
echo "SSH into production server and run:"
echo "  python scripts/fix_production_idempotency.py"
echo ""
echo "Expected output:"
echo "  🔗 Connecting to database..."
echo "  ➕ Adding idempotency_key column..."
echo "  ✅ Successfully added idempotency_key column and index"
echo ""
read -p "Press Enter when migration is complete..."

# Step 4: Restart Services
echo ""
echo "🔄 Step 4: Restart Application"
echo "On Render.com:"
echo "  1. Go to Dashboard > Your Service"
echo "  2. Click 'Manual Deploy' > 'Clear build cache & deploy'"
echo "  OR"
echo "  3. Click 'Restart Service'"
echo ""
read -p "Press Enter when services are restarted..."

# Step 5: Verify
echo ""
echo "✅ Step 5: Verification Tests"
echo ""
echo "Test 1: Check logs for startup success"
echo "  Look for: 'SMS polling service started'"
echo "  Look for: 'Voice polling service started'"
echo ""
echo "Test 2: Create a test verification"
echo "  curl -X POST https://namaskah.onrender.com/api/v1/verify/create \\"
echo "    -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"service_name\":\"telegram\",\"country\":\"US\"}'"
echo ""
echo "Test 3: Check database"
echo "  SELECT column_name FROM information_schema.columns"
echo "  WHERE table_name = 'verifications' AND column_name = 'idempotency_key';"
echo ""

read -p "Press Enter to see rollback instructions..."

# Rollback Instructions
echo ""
echo "🔙 ROLLBACK INSTRUCTIONS (if needed)"
echo "======================================"
echo ""
echo "If deployment fails:"
echo ""
echo "1. Revert code:"
echo "   git revert HEAD"
echo "   git push origin main"
echo ""
echo "2. Remove database column:"
echo "   ALTER TABLE verifications DROP COLUMN idempotency_key;"
echo "   DROP INDEX IF EXISTS ix_verifications_idempotency_key;"
echo ""
echo "3. Restore from backup:"
echo "   psql \$DATABASE_URL < backup_TIMESTAMP.sql"
echo ""
echo "======================================"
echo "✅ Deployment Guide Complete"
echo "======================================"
