"""Add rental system

Revision ID: 0320b211ff27
Revises: 003
Create Date: 2025-11-04 00:59:16.843214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0320b211ff27'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_status_last_checked'), table_name='service_status')
    op.drop_index(op.f('ix_service_status_service_name'), table_name='service_status')
    op.drop_table('service_status')
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_verifications_service_name'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_status'), table_name='verifications')
    op.drop_table('verifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verifications',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('service_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('capability', sa.VARCHAR(length=10), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('verification_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cost', sa.FLOAT(), nullable=False),
    sa.Column('call_duration', sa.FLOAT(), nullable=True),
    sa.Column('transcription', sa.VARCHAR(), nullable=True),
    sa.Column('audio_url', sa.VARCHAR(), nullable=True),
    sa.Column('requested_carrier', sa.VARCHAR(length=50), nullable=True),
    sa.Column('requested_area_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('country', sa.VARCHAR(), server_default=sa.text("'US'"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_status'), 'verifications', ['status'], unique=False)
    op.create_index(op.f('ix_verifications_service_name'), 'verifications', ['service_name'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('admin_response', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('email_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('credits', sa.FLOAT(), nullable=True),
    sa.Column('free_verifications', sa.FLOAT(), nullable=True),
    sa.Column('verification_token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('reset_token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DATETIME(), nullable=True),
    sa.Column('referral_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('referred_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('referral_earnings', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=1)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.create_table('api_keys',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('last_used', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=1)
    op.create_table('transactions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    op.create_table('service_status',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('service_name', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('success_rate', sa.FLOAT(), nullable=False),
    sa.Column('last_checked', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_status_service_name'), 'service_status', ['service_name'], unique=False)
    op.create_index(op.f('ix_service_status_last_checked'), 'service_status', ['last_checked'], unique=False)
    # ### end Alembic commands ###