"""Add soft delete columns

Revision ID: f6a9a9aafab3
Revises: 005_add_performance_indexes
Create Date: 2025-11-22 07:14:37.781356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f6a9a9aafab3'
down_revision = '005_add_performance_indexes'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rentals_status'), table_name='rentals')
    op.drop_index(op.f('ix_rentals_user_id'), table_name='rentals')
    op.drop_table('rentals')
    op.drop_index(op.f('ix_user_sessions_created_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('kyc_verification_limits')
    op.drop_index(op.f('ix_auth_audit_logs_timestamp'), table_name='auth_audit_logs')
    op.drop_index(op.f('ix_auth_audit_logs_user_id'), table_name='auth_audit_logs')
    op.drop_table('auth_audit_logs')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_timestamp'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_aml_screenings_kyc_profile_id'), table_name='aml_screenings')
    op.drop_table('aml_screenings')
    op.drop_index(op.f('ix_account_lockouts_email'), table_name='account_lockouts')
    op.drop_table('account_lockouts')
    op.drop_index(op.f('ix_biometric_verifications_kyc_profile_id'), table_name='biometric_verifications')
    op.drop_table('biometric_verifications')
    op.drop_index(op.f('ix_kyc_documents_file_hash'), table_name='kyc_documents')
    op.drop_index(op.f('ix_kyc_documents_kyc_profile_id'), table_name='kyc_documents')
    op.drop_table('kyc_documents')
    op.drop_index(op.f('ix_sms_messages_is_read'), table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_received_at'), table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_user_id'), table_name='sms_messages')
    op.drop_table('sms_messages')
    op.drop_index(op.f('ix_sms_forwarding_user_id'), table_name='sms_forwarding')
    op.drop_table('sms_forwarding')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_waitlist_email'), table_name='waitlist')
    op.drop_table('waitlist')
    op.drop_index(op.f('ix_kyc_profiles_status'), table_name='kyc_profiles')
    op.drop_index(op.f('ix_kyc_profiles_user_id'), table_name='kyc_profiles')
    op.drop_table('kyc_profiles')
    op.add_column('activity_logs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('activity_logs', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('affiliate_applications', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('affiliate_applications', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('affiliate_applications', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('affiliate_applications', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_affiliate_applications_email'), table_name='affiliate_applications')
    op.add_column('affiliate_commissions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('affiliate_commissions', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('affiliate_commissions', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('affiliate_commissions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_affiliate_commissions_affiliate_id'), table_name='affiliate_commissions')
    op.drop_index(op.f('ix_affiliate_commissions_status'), table_name='affiliate_commissions')
    op.drop_constraint(None, 'affiliate_commissions', type_='foreignkey')
    op.create_foreign_key(None, 'affiliate_commissions', 'users', ['affiliate_id'], ['id'])
    op.add_column('affiliate_programs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('affiliate_programs', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('affiliate_programs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.add_column('api_keys', sa.Column('key', sa.String(), nullable=False))
    op.add_column('api_keys', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('api_keys', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('api_keys', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_column('api_keys', 'key_hash')
    op.drop_column('api_keys', 'expires_at')
    op.drop_column('api_keys', 'last_used')
    op.drop_column('api_keys', 'prefix')
    op.add_column('banned_numbers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('banned_numbers', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('bulk_operations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('bulk_operations', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('commission_tiers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('commission_tiers', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('credit_allocations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('credit_allocations', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('enterprise_accounts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('enterprise_accounts', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('enterprise_accounts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_enterprise_accounts_user_id'), table_name='enterprise_accounts')
    op.drop_constraint(None, 'enterprise_accounts', type_='foreignkey')
    op.drop_constraint(None, 'enterprise_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'enterprise_accounts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'enterprise_accounts', 'enterprise_tiers', ['tier_id'], ['id'])
    op.add_column('enterprise_tiers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('enterprise_tiers', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('enterprise_tiers', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_enterprise_tiers_name'), table_name='enterprise_tiers')
    op.add_column('in_app_notifications', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('in_app_notifications', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('notification_preferences', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('notification_preferences', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('notification_settings', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('notification_settings', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('number_rentals', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('number_rentals', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('partner_features', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('partner_features', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('payment_logs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('payment_logs', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('payout_requests', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('payout_requests', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('personal_numbers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('personal_numbers', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('referrals', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('referrals', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('reseller_accounts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('reseller_accounts', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('revenue_shares', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('revenue_shares', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('service_status', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('service_status', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('sub_account_transactions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('sub_account_transactions', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('sub_accounts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('sub_accounts', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('subscriptions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('support_tickets', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('support_tickets', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('support_tickets', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('support_tickets', 'admin_response',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('support_tickets', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_constraint(None, 'support_tickets', type_='foreignkey')
    op.add_column('transactions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('users', 'credits',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('users', 'free_verifications',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_moderator',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'referral_earnings',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('users', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'is_affiliate',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_provider'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'mfa_enabled')
    op.add_column('verification_receipts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('verification_receipts', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('verifications', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('verifications', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('verifications', 'country',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('verifications', 'capability',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('verifications', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('verifications', 'transcription',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('verifications', 'activation_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('verifications', 'sms_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('verifications', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_verifications_activation_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_created_at'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_provider'), table_name='verifications')
    op.drop_constraint(None, 'verifications', type_='foreignkey')
    op.add_column('webhooks', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('webhooks', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('whitelabel_assets', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('whitelabel_assets', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('whitelabel_configs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('whitelabel_configs', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('whitelabel_configs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.drop_index(op.f('ix_whitelabel_configs_domain'), table_name='whitelabel_configs')
    op.create_index(op.f('ix_whitelabel_configs_domain'), 'whitelabel_configs', ['domain'], unique=True)
    op.add_column('whitelabel_domains', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('whitelabel_domains', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('whitelabel_themes', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('whitelabel_themes', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whitelabel_themes', 'is_deleted')
    op.drop_column('whitelabel_themes', 'deleted_at')
    op.drop_column('whitelabel_domains', 'is_deleted')
    op.drop_column('whitelabel_domains', 'deleted_at')
    op.drop_index(op.f('ix_whitelabel_configs_domain'), table_name='whitelabel_configs')
    op.create_index(op.f('ix_whitelabel_configs_domain'), 'whitelabel_configs', ['domain'], unique=False)
    op.alter_column('whitelabel_configs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_column('whitelabel_configs', 'is_deleted')
    op.drop_column('whitelabel_configs', 'deleted_at')
    op.drop_column('whitelabel_assets', 'is_deleted')
    op.drop_column('whitelabel_assets', 'deleted_at')
    op.drop_column('webhooks', 'is_deleted')
    op.drop_column('webhooks', 'deleted_at')
    op.create_foreign_key(None, 'verifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_verifications_provider'), 'verifications', ['provider'], unique=False)
    op.create_index(op.f('ix_verifications_created_at'), 'verifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_verifications_activation_id'), 'verifications', ['activation_id'], unique=False)
    op.alter_column('verifications', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('verifications', 'sms_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('verifications', 'activation_id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('verifications', 'transcription',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('verifications', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('verifications', 'capability',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('verifications', 'country',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.drop_column('verifications', 'is_deleted')
    op.drop_column('verifications', 'deleted_at')
    op.drop_column('verification_receipts', 'is_deleted')
    op.drop_column('verification_receipts', 'deleted_at')
    op.add_column('users', sa.Column('mfa_enabled', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('mfa_secret', sa.VARCHAR(length=32), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_provider'), 'users', ['provider'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'is_affiliate',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'referral_earnings',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_moderator',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'free_verifications',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('users', 'credits',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'deleted_at')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_column('transactions', 'is_deleted')
    op.drop_column('transactions', 'deleted_at')
    op.create_foreign_key(None, 'support_tickets', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('support_tickets', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('support_tickets', 'admin_response',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('support_tickets', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('support_tickets', 'is_deleted')
    op.drop_column('support_tickets', 'deleted_at')
    op.drop_column('subscriptions', 'is_deleted')
    op.drop_column('subscriptions', 'deleted_at')
    op.drop_column('sub_accounts', 'is_deleted')
    op.drop_column('sub_accounts', 'deleted_at')
    op.drop_column('sub_account_transactions', 'is_deleted')
    op.drop_column('sub_account_transactions', 'deleted_at')
    op.drop_column('service_status', 'is_deleted')
    op.drop_column('service_status', 'deleted_at')
    op.drop_column('revenue_shares', 'is_deleted')
    op.drop_column('revenue_shares', 'deleted_at')
    op.drop_column('reseller_accounts', 'is_deleted')
    op.drop_column('reseller_accounts', 'deleted_at')
    op.drop_column('referrals', 'is_deleted')
    op.drop_column('referrals', 'deleted_at')
    op.drop_column('personal_numbers', 'is_deleted')
    op.drop_column('personal_numbers', 'deleted_at')
    op.drop_column('payout_requests', 'is_deleted')
    op.drop_column('payout_requests', 'deleted_at')
    op.drop_column('payment_logs', 'is_deleted')
    op.drop_column('payment_logs', 'deleted_at')
    op.drop_column('partner_features', 'is_deleted')
    op.drop_column('partner_features', 'deleted_at')
    op.drop_column('number_rentals', 'is_deleted')
    op.drop_column('number_rentals', 'deleted_at')
    op.drop_column('notification_settings', 'is_deleted')
    op.drop_column('notification_settings', 'deleted_at')
    op.drop_column('notification_preferences', 'is_deleted')
    op.drop_column('notification_preferences', 'deleted_at')
    op.drop_column('in_app_notifications', 'is_deleted')
    op.drop_column('in_app_notifications', 'deleted_at')
    op.create_index(op.f('ix_enterprise_tiers_name'), 'enterprise_tiers', ['name'], unique=False)
    op.alter_column('enterprise_tiers', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_column('enterprise_tiers', 'is_deleted')
    op.drop_column('enterprise_tiers', 'deleted_at')
    op.drop_constraint(None, 'enterprise_accounts', type_='foreignkey')
    op.drop_constraint(None, 'enterprise_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'enterprise_accounts', 'enterprise_tiers', ['tier_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'enterprise_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_enterprise_accounts_user_id'), 'enterprise_accounts', ['user_id'], unique=False)
    op.alter_column('enterprise_accounts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_column('enterprise_accounts', 'is_deleted')
    op.drop_column('enterprise_accounts', 'deleted_at')
    op.drop_column('credit_allocations', 'is_deleted')
    op.drop_column('credit_allocations', 'deleted_at')
    op.drop_column('commission_tiers', 'is_deleted')
    op.drop_column('commission_tiers', 'deleted_at')
    op.drop_column('bulk_operations', 'is_deleted')
    op.drop_column('bulk_operations', 'deleted_at')
    op.drop_column('banned_numbers', 'is_deleted')
    op.drop_column('banned_numbers', 'deleted_at')
    op.add_column('api_keys', sa.Column('prefix', sa.VARCHAR(length=10), nullable=False))
    op.add_column('api_keys', sa.Column('last_used', sa.DATETIME(), nullable=True))
    op.add_column('api_keys', sa.Column('expires_at', sa.DATETIME(), nullable=True))
    op.add_column('api_keys', sa.Column('key_hash', sa.VARCHAR(length=255), nullable=False))
    op.create_foreign_key(None, 'api_keys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.alter_column('api_keys', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('api_keys', 'is_deleted')
    op.drop_column('api_keys', 'deleted_at')
    op.drop_column('api_keys', 'key')
    op.alter_column('affiliate_programs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_column('affiliate_programs', 'is_deleted')
    op.drop_column('affiliate_programs', 'deleted_at')
    op.drop_constraint(None, 'affiliate_commissions', type_='foreignkey')
    op.create_foreign_key(None, 'affiliate_commissions', 'users', ['affiliate_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_affiliate_commissions_status'), 'affiliate_commissions', ['status'], unique=False)
    op.create_index(op.f('ix_affiliate_commissions_affiliate_id'), 'affiliate_commissions', ['affiliate_id'], unique=False)
    op.alter_column('affiliate_commissions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('affiliate_commissions', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('affiliate_commissions', 'is_deleted')
    op.drop_column('affiliate_commissions', 'deleted_at')
    op.create_index(op.f('ix_affiliate_applications_email'), 'affiliate_applications', ['email'], unique=False)
    op.alter_column('affiliate_applications', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('affiliate_applications', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('affiliate_applications', 'is_deleted')
    op.drop_column('affiliate_applications', 'deleted_at')
    op.drop_column('activity_logs', 'is_deleted')
    op.drop_column('activity_logs', 'deleted_at')
    op.create_table('kyc_profiles',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('verification_level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('nationality', sa.VARCHAR(length=3), nullable=True),
    sa.Column('address_line1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('address_line2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('country', sa.VARCHAR(length=3), nullable=True),
    sa.Column('submitted_at', sa.DATETIME(), nullable=True),
    sa.Column('verified_at', sa.DATETIME(), nullable=True),
    sa.Column('rejected_at', sa.DATETIME(), nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), nullable=True),
    sa.Column('risk_score', sa.FLOAT(), nullable=True),
    sa.Column('aml_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('pep_status', sa.BOOLEAN(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True),
    sa.Column('verification_notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_kyc_profiles_user_id'), 'kyc_profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_kyc_profiles_status'), 'kyc_profiles', ['status'], unique=False)
    op.create_table('waitlist',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_notified', sa.BOOLEAN(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_waitlist_email'), 'waitlist', ['email'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('sms_forwarding',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('rental_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('telegram_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone_enabled', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False),
    sa.Column('email_enabled', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False),
    sa.Column('telegram_enabled', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_forwarding_user_id'), 'sms_forwarding', ['user_id'], unique=False)
    op.create_table('sms_messages',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('rental_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('from_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('received_at', sa.DATETIME(), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_sms_messages_user_id'), 'sms_messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_sms_messages_received_at'), 'sms_messages', ['received_at'], unique=False)
    op.create_index(op.f('ix_sms_messages_is_read'), 'sms_messages', ['is_read'], unique=False)
    op.create_table('kyc_documents',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('kyc_profile_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('document_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('document_expiry', sa.DATE(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_size', sa.FLOAT(), nullable=True),
    sa.Column('file_hash', sa.VARCHAR(length=64), nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('verification_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('verification_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('extracted_data', sqlite.JSON(), nullable=True),
    sa.Column('ocr_text', sa.TEXT(), nullable=True),
    sa.Column('is_encrypted', sa.BOOLEAN(), nullable=True),
    sa.Column('access_count', sa.INTEGER(), nullable=True),
    sa.Column('last_accessed', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['kyc_profile_id'], ['kyc_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_index(op.f('ix_kyc_documents_kyc_profile_id'), 'kyc_documents', ['kyc_profile_id'], unique=False)
    op.create_index(op.f('ix_kyc_documents_file_hash'), 'kyc_documents', ['file_hash'], unique=False)
    op.create_table('biometric_verifications',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('kyc_profile_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('verification_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('reference_image_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('verification_image_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('match_score', sa.FLOAT(), nullable=True),
    sa.Column('liveness_score', sa.FLOAT(), nullable=True),
    sa.Column('verification_result', sa.VARCHAR(length=20), nullable=True),
    sa.Column('confidence_level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('algorithm_used', sa.VARCHAR(length=100), nullable=True),
    sa.Column('processing_time', sa.FLOAT(), nullable=True),
    sa.Column('quality_scores', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['kyc_profile_id'], ['kyc_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biometric_verifications_kyc_profile_id'), 'biometric_verifications', ['kyc_profile_id'], unique=False)
    op.create_table('account_lockouts',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('locked_until', sa.DATETIME(), nullable=True),
    sa.Column('reason', sa.VARCHAR(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_account_lockouts_email'), 'account_lockouts', ['email'], unique=1)
    op.create_table('aml_screenings',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('kyc_profile_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('screening_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('match_score', sa.FLOAT(), nullable=True),
    sa.Column('matches_found', sqlite.JSON(), nullable=True),
    sa.Column('search_terms', sqlite.JSON(), nullable=True),
    sa.Column('data_sources', sqlite.JSON(), nullable=True),
    sa.Column('screening_provider', sa.VARCHAR(length=50), nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('review_decision', sa.VARCHAR(length=20), nullable=True),
    sa.Column('review_notes', sa.TEXT(), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['kyc_profile_id'], ['kyc_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aml_screenings_kyc_profile_id'), 'aml_screenings', ['kyc_profile_id'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_timestamp'), 'login_attempts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_table('auth_audit_logs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('details', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_audit_logs_user_id'), 'auth_audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_auth_audit_logs_timestamp'), 'auth_audit_logs', ['timestamp'], unique=False)
    op.create_table('kyc_verification_limits',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('verification_level', sa.VARCHAR(length=20), nullable=False),
    sa.Column('daily_limit', sa.FLOAT(), nullable=False),
    sa.Column('monthly_limit', sa.FLOAT(), nullable=False),
    sa.Column('annual_limit', sa.FLOAT(), nullable=False),
    sa.Column('allowed_services', sqlite.JSON(), nullable=True),
    sa.Column('max_transaction_amount', sa.FLOAT(), nullable=True),
    sa.Column('requires_additional_auth', sa.BOOLEAN(), nullable=True),
    sa.Column('country_restrictions', sqlite.JSON(), nullable=True),
    sa.Column('service_restrictions', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_level')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=True),
    sa.Column('refresh_token', sa.VARCHAR(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_created_at'), 'user_sessions', ['created_at'], unique=False)
    op.create_table('rentals',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('service_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=3), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=20), nullable=True),
    sa.Column('activation_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=4), nullable=False),
    sa.Column('duration_hours', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rentals_user_id'), 'rentals', ['user_id'], unique=False)
    op.create_index(op.f('ix_rentals_status'), 'rentals', ['status'], unique=False)
    # ### end Alembic commands ###