[program:vrenum]
command=/home/vrenum/app/.venv/bin/gunicorn main:app
    --workers 3
    --worker-class uvicorn.workers.UvicornWorker
    --bind 127.0.0.1:8000
    --timeout 120
    --graceful-timeout 30
    --keep-alive 5
    --access-logfile /var/log/vrenum/access.log
    --error-logfile /var/log/vrenum/error.log
    --log-level info
directory=/home/vrenum/app
user=vrenum
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
environment=
    HOME="/home/vrenum",
    PATH="/home/vrenum/app/.venv/bin"
stdout_logfile=/var/log/vrenum/supervisor.log
stderr_logfile=/var/log/vrenum/supervisor_err.log
